#!/bin/bash

# Vultr deployment script for szkmpztrv React SPA
# This script is now replaced by the Makefile for easier deployment
# Use: make setup SERVER=username@SERVER-IP

echo "🚀 szkmpztrv deployment script"
echo ""
echo "This script has been replaced by the Makefile for easier deployment."
echo ""
echo "To deploy your application:"
echo ""
echo "1. Initial server setup:"
echo "   make setup SERVER=root@YOUR_SERVER_IP"
echo ""
echo "2. Deploy updates:"
echo "   make deploy SERVER=root@YOUR_SERVER_IP"
echo ""
echo "3. Quick deploy (without building):"
echo "   make quick-deploy SERVER=root@YOUR_SERVER_IP"
echo ""
echo "4. Check server status:"
echo "   make status SERVER=root@YOUR_SERVER_IP"
echo ""
echo "5. View help:"
echo "   make help"
echo ""
echo "Example:"
echo "   make setup SERVER=root@192.168.1.100"
echo ""
echo "The Makefile will handle all the deployment steps automatically!"
echo ""
echo "Make sure to:"
echo "1. Update the domain in nginx.conf"
echo "2. Set up SSL with Let's Encrypt"
echo "3. Configure GitHub Actions secrets for CI/CD"
